version: '3.8'

services:

  traefik:
    image: traefik:v2.10
    container_name: traefik
    labels:
      - traefik.enable=false
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"  # Traefik dashboard
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  backend:
    image: backend
    container_name: backend
    build: "./backend"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.entrypoints=web"
      - "traefik.http.routers.backend.rule=PathPrefix(`/healthcheck`, `/backend`)"
      - "traefik.http.routers.backend.service=backend"
      - "traefik.http.services.backend.loadbalancer.server.port=4000"
    volumes:
      - ./backend:/app
      - uploads:/app/uploads

  frontend:
    image: frontend
    container_name: frontend
    build: ./frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.routers.frontend.rule=PathPrefix(`/`)"
      - "traefik.http.routers.frontend.service=frontend"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"
    volumes:
      - ./frontend:/app

volumes:
  uploads: